// Generated by CoffeeScript 1.10.0
(function() {
  window.Person = (function() {
    function Person(name) {
      this.name = name;
    }

    Person.prototype.possessiveName = function() {
      var ref;
      if ((ref = this.name[this.name.length - 1]) === 's' || ref === 'x' || ref === 'z') {
        return this.name + "'";
      } else {
        return this.name + "'s";
      }
    };

    return Person;

  })();

}).call(this);
