// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.PetView = (function(superClass) {
    extend(PetView, superClass);

    function PetView(pet) {
      this.pet = pet;
    }

    PetView.prototype.formattedDescription = function() {
      var ref;
      return ("<h2>" + this.pet.name + "</h2>") + ("<h3 class='breed'>" + this.pet.breed + " ") + ("(" + ((ref = this.pet.age) != null ? ref : "??") + " years old)</h3>") + this.imageTag(this.pet.image) + ("<p class='description'>" + this.pet.description + "</p>");
    };

    PetView.prototype.formattedName = function(showBehavior) {
      var action, behavior, cssClass, ref, ref1, result, sound;
      result = this.pet.name;
      if (showBehavior) {
        ref = this.pet.behaviors(), sound = ref[0], action = ref[1];
        ref1 = sound != null ? [sound + "!", "sound"] : [action, "action"], behavior = ref1[0], cssClass = ref1[1];
        result += " <span class='" + cssClass + "'>" + (behavior.toLowerCase()) + "</span>";
      }
      return result;
    };

    PetView.prototype.formattedLink = function(i, showBehavior) {
      if (showBehavior == null) {
        showBehavior = true;
      }
      return ("<a href='#' onclick='selectPet(" + i + ", this)'>") + ((this.formattedName(showBehavior)) + "</a>");
    };

    return PetView;

  })(View);

}).call(this);
