// Generated by CoffeeScript 1.10.0
(function() {
  var ref;

  window.Test = (function() {
    function Test() {}

    Test.prototype.possessiveName = function() {
      var ref;
      if ((ref = this.name[this.name.length - 1]) === 's' || ref === 'x' || ref === 'z') {
        return this.name + "'";
      } else {
        return this.name + "'s";
      }
    };

    Test.prototype.possessivePassword = function() {};

    return Test;

  })();

  if ((ref = this.name[this.name.length - 1]) === 's' || ref === 'x' || ref === 'z') {
    this.name + "'";
  } else {
    this.name + "'s";
  }

}).call(this);
