// Generated by CoffeeScript 1.10.0
(function() {
  window.View = (function() {
    function View() {}

    View.prototype.renderToElement = function(id, output) {
      var el;
      el = document.getElementById(id);
      return el.innerHTML = output;
    };

    View.prototype.imageTag = function(filename) {
      if (filename != null) {
        return "<img src='images/" + filename + "' />";
      } else {
        return "";
      }
    };

    return View;

  })();

}).call(this);
